# Generated by Django 4.2.6 on 2023-12-26 06:29

import atm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_cnic', models.CharField(max_length=15)),
                ('user_mobile', models.CharField(max_length=12)),
                ('user_account_number', models.CharField(default=atm.models.AccDetail.generate_10_uuid, max_length=10, unique=True)),
                ('user_city', models.CharField(max_length=30)),
                ('user_address', models.TextField(max_length=200)),
                ('buser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
